"
A CBFalsePositiveCriticActionTest is a test class for testing the behavior of CBFalsePositiveCriticAction
"
Class {
	#name : #CBFalsePositiveCriticActionTest,
	#superclass : #CBAbstractButtonActionTest,
	#category : #'Migrate-Tool-CriticBrowser-Tests'
}

{ #category : #running }
CBFalsePositiveCriticActionTest >> setUp [
	"Hooks that subclasses may override to define the fixture of test."
	super setUp
]
