"
A CBTransformCriticActionTest is a test class for testing the behavior of CBTransformCriticAction
"
Class {
	#name : #CBTransformCriticActionTest,
	#superclass : #CBAbstractButtonActionTest,
	#category : #'Migrate-Tool-CriticBrowser-Tests-Test-Button'
}

{ #category : #running }
CBTransformCriticActionTest >> setUp [
	"Hooks that subclasses may override to define the fixture of test."
	super setUp
]
