Class {
	#name : #SycMockRBRefactoring,
	#superclass : #Object,
	#category : #'Stage-Tests-util'
}

{ #category : #accessing }
SycMockRBRefactoring >> environment: anEnvironement [
	^ self
]

{ #category : #accessing }
SycMockRBRefactoring >> model [
	^ self
]

{ #category : #accessing }
SycMockRBRefactoring >> primitiveExecute [ 
	^self 
]

{ #category : #accessing }
SycMockRBRefactoring >> whatToDisplayIn: aThing [
	^ true
]
